version: "3.8"
services:
    nodejsapp:
        build:
            context: ./app
        ports:
            - "3000:3000"
        networks:
            - mynetwork
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        networks:
            - mynetwork
networks:
  mynetwork:
    driver: bridge